"""Persistent MongoDB access settings, stored in the HostPanel core SQLite DB.

mongod.conf is regenerated by the package on every install/update, so the
security posture (auth enforcement, bind scope) and the panel's own admin
credential must live here and be re-applied — otherwise a package update
would silently reset an exposed server back to an open one.
"""
from __future__ import annotations

from typing import Optional

from db import get_conn


def _migrate() -> None:
    with get_conn() as conn:
        conn.execute(
            "CREATE TABLE IF NOT EXISTS mongodb_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)"
        )


def get(key: str, default: Optional[str] = None) -> Optional[str]:
    _migrate()
    with get_conn() as conn:
        row = conn.execute("SELECT value FROM mongodb_settings WHERE key=?", (key,)).fetchone()
    return row["value"] if row else default


def set(key: str, value: str) -> None:
    _migrate()
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO mongodb_settings (key, value) VALUES (?, ?) "
            "ON CONFLICT(key) DO UPDATE SET value=excluded.value",
            (key, value),
        )


def auth_enabled() -> bool:
    return get("auth_enabled", "0") == "1"


def bind_ip() -> str:
    return get("bind_ip", "127.0.0.1") or "127.0.0.1"


def admin_credentials() -> Optional[tuple[str, str]]:
    """The panel's own root credential, minted when auth enforcement was
    first enabled. None while enforcement has never been turned on."""
    user = get("admin_user")
    password = get("admin_pass")
    return (user, password) if user and password else None
